### ISSUE TITLE
XP Drop colour not changing while using godsword and piety

### ISSUE THREAD

**Issue by spookychini** [l2-/template-plugin#102]
Mine is usually set to red when using a melee weapon and piety. Works for other weapons but not godswords.

**Comment by an-aprilia** [comment]
I can confirm this does not work for godswords. Bug can also be reproduced with the Abyssal Bludgeon.

Reproduction Steps:

1. Equip Abyssal Bludgeon or Bandos Godsword
2. Turn on Piety
3. Attack an NPC

Expected: XP drop is colored based on plugin settings for "XP drop color melee". 
Observed: XP drop is colored based on default drop color, "XP drop color"

![image](https://github.com/l2-/template-plugin/assets/164449330/9d6844e3-0ff0-4aae-9f2e-19ee08dbf502)

**Comment by QGoh** [comment]
Same issue also exists with Keris Partisan of Breaching.

**Comment by l2-** [comment]
Hopefully fixed with the merging of https://github.com/runelite/plugin-hub/pull/5733

**Comment by DuayneDibbley** [comment]
Just tested again and doesn't seem to be fixed. Tested with SGS and BGS

**Comment by hawkins** [comment]
I am also still seeing this bug with the Keris Partisan of Breaching
